---
  # Parameters:
  #  prudentia_dir (provided)

  - name: Chrome | Add GPG key to apt keyring
    shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    when: ansible_os_family == "Debian"
    tags:
      - chrome
    become: yes

  - name: Chrome | Add apt repository
    copy: src={{prudentia_dir}}/files/chrome/apt-source dest=/etc/apt/sources.list.d/google-chrome.list mode=644
    when: ansible_os_family == "Debian"
    tags:
      - chrome
    become: yes

  - name: Chrome | Install last stable
    apt: update-cache=yes force=yes state=present pkg=google-chrome-stable
    when: ansible_os_family == "Debian"
    tags:
      - chrome
    become: yes
