---
  - name: Nginx | Add GPG key to apt keyring
    shell: wget -q -O - http://nginx.org/keys/nginx_signing.key | sudo apt-key add -
    when: ansible_os_family == "Debian"
    tags: nginx
    sudo: yes

  - name: Nginx | Add Debian apt repository
    apt_repository: repo="deb http://nginx.org/packages/debian/ {{ansible_distribution_release}} nginx"
    when: ansible_os_family == "Debian" and ansible_distribution != "Ubuntu"
    tags: nginx
    sudo: yes

  - name: Nginx | Add Ubuntu apt repository
    apt_repository: repo="deb http://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx"
    when: ansible_distribution == "Ubuntu"
    tags: nginx
    sudo: yes

  - name: Nginx | Install
    apt: update-cache=yes force=yes state=present pkg=nginx
    when: ansible_os_family == "Debian"
    tags: nginx
    sudo: yes

  - name: Nginx | Create sites available/enabled directories
    file: path={{item}} state=directory mode=0755
    with_items:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
    when: ansible_os_family == "Debian"
    tags: nginx
    sudo: yes

  - name: Nginx | Configure include sites-enabled
    lineinfile: dest=/etc/nginx/nginx.conf regexp=".*sites-enabled.*" line="    include /etc/nginx/sites-enabled/*;" insertbefore="}" state=present
    when: ansible_os_family == "Debian"
    tags: nginx
    sudo: yes
