---
  # Parameters:
  #  osquery_apt_key_id (provided)
  #  osquery_apt_repository (provided)

  - name: OSQuery | Check if is installed
    command: test -x /usr/bin/osqueryd
    when: ansible_system == "Linux"
    register: osquery_present
    ignore_errors: yes
    tags:
      - osquery

  - name: OSQuery | Add apt repository key
    apt_key: id={{osquery_apt_key_id}} keyserver=keyserver.ubuntu.com state=present
    when: ansible_os_family == "Debian" and osquery_present|failed
    become: yes
    tags:
      - osquery

  - name: OSQuery | Add apt repository
    apt_repository: repo="{{osquery_apt_repository}}" state=present
    when: ansible_os_family == "Debian" and osquery_present|failed
    become: yes
    tags:
      - osquery

  - name: OSQuery | Install
    apt: update-cache=yes force=yes state=present pkg={{item}}
    with_items:
      - osquery
      - libcryptsetup-dev
      - gcc-4.9
    when: ansible_os_family == "Debian" and osquery_present|failed
    become: yes
    tags:
      - osquery
